"""Listing generation. Pure formatting — no analysis decisions are made here.

Output targets asl (Macro Assembler AS) syntax and is also accepted verbatim by
dis65xx.asm, which is what enforces byte-identity.
"""

from __future__ import annotations

import dataclasses

from dis65xx.decode import Insn
from dis65xx.opcodes import Mode, modes_for
from dis65xx.sidecar import Sidecar
from dis65xx.trace import CODE, TraceResult

BYTES_PER_FCB = 16
_INDENT = 8      # leading spaces before a mnemonic
_MNEM_WIDTH = 8  # column width the mnemonic is padded to


_JUMPS = ("JMP", "JSR")


def collect_targets(data: bytes, result: TraceResult, sidecar: Sidecar) -> dict[int, str]:
    """Auto-label every branch and jump target that has no name of its own.

    Named L<addr>, so a target reads as a label instead of a bare address. Only
    addresses inside the image qualify. The 6502 blocks are assembled from their
    own sources and linked in as binary, so nothing here needs to know about
    them.
    """
    base = result.base
    end = base + len(data)
    targets: set[int] = set()

    for insn in result.insns.values():
        if insn.mode is Mode.REL:
            targets.add(insn.operand)
        elif insn.mnemonic in _JUMPS and insn.mode in (Mode.EXT, Mode.DIR):
            targets.add(insn.operand)


    return {a: f"L{a:04X}" for a in targets
            if base <= a < end and a not in sidecar.labels}


def format_operand(insn: Insn, sidecar: Sidecar) -> str:
    mode = insn.mode
    value = insn.operand

    if mode is Mode.INH:
        return ""
    if mode is Mode.IMM8:
        return f"#${value:02X}"
    if mode is Mode.IMM16:
        return f"#${value:04X}"
    if mode is Mode.IDX:
        return f"${value:02X},X"
    if mode is Mode.REL:
        return sidecar.labels.get(value) or f"${value:04X}"
    if mode is Mode.DIR:
        return sidecar.symbols.get(value) or f"${value:02X}"
    if mode is Mode.EXT:
        name = sidecar.symbols.get(value) or sidecar.labels.get(value)
        # Force extended when a shortest-fit assembler would choose direct.
        prefix = ">" if value < 0x100 and Mode.DIR in modes_for(insn.mnemonic) else ""
        return prefix + (name if name else f"${value:04X}")

    raise AssertionError(f"unhandled mode {mode}")  # pragma: no cover


def _instruction_line(insn: Insn, sidecar: Sidecar) -> str:
    operand = format_operand(insn, sidecar)
    body = f"{'':{_INDENT}}{insn.mnemonic:{_MNEM_WIDTH}}{operand}".rstrip()
    comment = sidecar.line_comments.get(insn.addr)
    return f"{body:<40}; {comment}" if comment else body


def _fcb_line(chunk: bytes) -> str:
    values = ",".join(f"${b:02X}" for b in chunk)
    return f"{'':{_INDENT}}{'FCB':{_MNEM_WIDTH}}{values}"


def _equ_lines(sidecar: Sidecar) -> list[str]:
    """Declare sidecar symbols so the listing is self-contained.

    format_operand() renders hardware registers and RAM locations by name. Those
    addresses live outside the ROM image, so unlike code labels nothing in the
    listing defines them — without these EQUs the listing does not assemble.
    """
    if not sidecar.symbols:
        return []
    width = max(len(n) for n in sidecar.symbols.values())
    lines = ["; Hardware registers and RAM locations referenced below.", ""]
    for addr, name in sorted(sidecar.symbols.items()):
        value = f"${addr:02X}" if addr < 0x100 else f"${addr:04X}"
        lines.append(f"{name:{max(width, _INDENT - 1)}} EQU     {value}")
    lines.append("")
    return lines


def _fdb_line(words: list[int]) -> str:
    values = ",".join(f"${w:04X}" for w in words)
    return f"{'':{_INDENT}}{'FDB':{_MNEM_WIDTH}}{values}"


def emit(data: bytes, result: TraceResult, sidecar: Sidecar) -> str:
    # Branch and jump targets become labels. The sidecar's own names win, so a
    # routine that has been identified keeps its name instead of an L-address.
    # Collecting changes the emitter's framing (a label splits an instruction),
    # which can expose branches that were not visible on the previous pass, so
    # iterate until the label set stops growing.
    auto = collect_targets(data, result, sidecar)
    sidecar = dataclasses.replace(sidecar, labels={**auto, **sidecar.labels})


    base = result.base
    lines: list[str] = [
        "; Commodore BTX Decoder II firmware",
        "; GENERATED by dis65xx from sidecar/decoder_ii.toml - DO NOT EDIT.",
        ";",
        "; Regenerate and verify with:  python3 build.py",
        "",
        f"{'':{_INDENT}}{'CPU':{_MNEM_WIDTH}}6801",
        "",
    ]
    lines += _equ_lines(sidecar)
    lines += [
        f"{'':{_INDENT}}{'ORG':{_MNEM_WIDTH}}${base:04X}",
        "",
    ]

    addr = base
    end = base + len(data)
    pending: list[int] = []  # unclassified bytes waiting to be flushed as FCB

    def flush() -> None:
        while pending:
            chunk = bytes(pending[:BYTES_PER_FCB])
            del pending[:BYTES_PER_FCB]
            lines.append(_fcb_line(chunk))

    while addr < end:
        label = sidecar.labels.get(addr)
        block = sidecar.block_comments.get(addr)
        region = sidecar.region_at(addr)
        insn = result.insns.get(addr)
        # An address the tracer decoded from is a real entry point even if an
        # overlapping instruction later marked its bytes as operand - that is
        # exactly the skip-chain case, where each stub is entered directly.
        is_code = insn is not None and (
            result.kind[addr - base] is CODE or addr in sidecar.labels)

        if label or block:
            flush()
            lines.append("")
            if block:
                for line in block.strip().splitlines():
                    lines.append(f"; {line}" if line else ";")
            if label:
                lines.append(f"{label}:")

        c64 = sidecar.c64_block_at(addr)
        if c64 is not None and addr == c64.start:
            flush()
            lines.append("")
            lines.append(f"; {c64.name}: 6502 code, assembled separately at "
                         f"${c64.org:04X}. See out/c64_{c64.name}.asm.")
            lines.append(f"{'':{_INDENT}}BINCLUDE \"c64_{c64.name}.bin\"")
            lines.append("")
            addr = c64.end
            continue

        if region is not None and region.kind in ("words", "ptr_table") and not is_code:
            flush()
            count = min(8, (min(region.end, end) - addr) // 2)
            if count:
                words = [
                    int.from_bytes(data[addr - base + 2 * i: addr - base + 2 * i + 2], "big")
                    for i in range(count)
                ]
                lines.append(_fdb_line(words))
                addr += 2 * count
                continue

        if is_code:
            # A label strictly inside this instruction is an overlapping entry
            # point - the skip-chain idiom, where a 3-byte CPX # swallows the
            # following stub. Emit the leading bytes as FCB so the label can sit
            # on its own address instead of being silently dropped.
            split = next((x for x in range(insn.addr + 1, insn.end)
                          if x in sidecar.labels or x in sidecar.block_comments), None)
            if split is not None:
                flush()
                lines.append(_fcb_line(data[addr - base:split - base])
                             + f"{'':<8}; overlapped by the entry point below")
                addr = split
                continue
            flush()
            lines.append(_instruction_line(insn, sidecar))
            addr = insn.end
            continue

        pending.append(data[addr - base])
        addr += 1
        # Break the FCB run at any address that carries its own annotation.
        if addr < end and (addr in sidecar.labels or addr in sidecar.block_comments):
            flush()

    flush()
    lines.append("")
    lines.append(f"{'':{_INDENT}}END")
    return "\n".join(lines) + "\n"
