"""Standalone 6502 source for a C64 block.

Assembled on its own at the address it really runs at, so every internal target
is an ordinary label at an ordinary address. That is the whole point of keeping
the two instruction sets in separate files: neither listing has to carry the
other's addressing quirks.
"""

from __future__ import annotations

from dis65xx import c64kernal, codec6502
from dis65xx.opcodes6502 import Mode
from dis65xx.sidecar import C64Block, Sidecar

BYTES_PER_FCB = 16
_INDENT = 8
_MNEM_WIDTH = 8
_JUMPS = ("JMP", "JSR")


def _operand(insn, labels: dict[int, str]) -> str:
    m, v = insn.mode, insn.operand
    if m is Mode.IMP:
        return ""
    if m is Mode.ACC:
        return "A"
    if m is Mode.IMM:
        return f"#${v:02X}"
    if m is Mode.ZP:
        return f"${v:02X}"
    if m is Mode.ZPX:
        return f"${v:02X},X"
    if m is Mode.ZPY:
        return f"${v:02X},Y"
    if m is Mode.IZX:
        return f"(${v:02X},X)"
    if m is Mode.IZY:
        return f"(${v:02X}),Y"
    if m is Mode.IND:
        return f"({labels.get(v) or f'${v:04X}'})"
    if m is Mode.REL:
        return labels.get(v) or f"${v:04X}"
    name = labels.get(v)
    pre = ">" if v < 0x100 and name is None else ""
    body = name or f"${v:04X}"
    if m is Mode.ABS:
        return pre + body
    if m is Mode.ABX:
        return pre + body + ",X"
    if m is Mode.ABY:
        return pre + body + ",Y"
    raise AssertionError(m)  # pragma: no cover


_DATA_KINDS = {"bytes", "string", "words", "ptr_table", "chargen"}


def _decode_block(data: bytes, base: int, block: C64Block, labels: dict[int, str],
                  sidecar: Sidecar | None = None):
    """Yield (runtime_addr, insn_or_None, byte) walking the block.

    A byte covered by a data region is never disassembled - that is what keeps
    the German text and the tables after the jump table from being rendered as
    nonsense instructions.
    """
    addr = block.start
    while addr < block.end:
        rt = addr - block.offset
        split = None
        region = sidecar.region_at(addr) if sidecar is not None else None
        if region is not None and region.kind in _DATA_KINDS:
            yield rt, None, data[addr - base]
            addr += 1
            continue
        try:
            insn = codec6502.decode(data, addr - base, rt)
        except ValueError:
            insn = None
        if insn is not None and addr + insn.size <= block.end:
            split = next((x for x in range(rt + 1, rt + insn.size) if x in labels), None)
        if insn is None or addr + insn.size > block.end or split is not None:
            yield rt, None, data[addr - base]
            addr += 1
            continue
        yield rt, insn, None
        addr += insn.size


def collect_labels(data: bytes, base: int, block: C64Block,
                   sidecar: Sidecar) -> dict[int, str]:
    """Named labels from the sidecar, plus L<addr> for every internal target."""
    named = {a - block.offset: n for a, n in sidecar.labels.items()
             if block.start <= a < block.end}
    labels = dict(named)
    for _ in range(8):
        targets: set[int] = set()
        for rt, insn, _b in _decode_block(data, base, block, labels, sidecar):
            if insn is None:
                continue
            if insn.mode is Mode.REL:
                targets.add(insn.operand)
            elif insn.mode is Mode.ABS and insn.mnemonic in _JUMPS:
                targets.add(insn.operand)
        found = dict(named)
        found.update({a: f"L{a:04X}" for a in targets
                      if block.org <= a < block.org + (block.end - block.start)
                      and a not in named})
        if found == labels:
            break
        labels = found
    else:
        raise ValueError(f"{block.name}: label collection did not converge")
    return labels


def emit_block(data: bytes, base: int, block: C64Block, sidecar: Sidecar) -> str:
    labels = collect_labels(data, base, block, sidecar)

    # External references: C64 ROM entry points and anything outside this block.
    external: dict[int, str] = {}
    for _rt, insn, _b in _decode_block(data, base, block, labels, sidecar):
        if insn is None or insn.operand is None:
            continue
        if insn.mode not in (Mode.ABS, Mode.IND) or insn.mnemonic not in _JUMPS:
            continue
        v = insn.operand
        if v in labels:
            continue
        name = c64kernal.name_for(v)
        if name:
            external[v] = name

    lines = [
        f"; C64 {block.name} - extracted from the BTX Decoder II ROM.",
        f"; Lives at ${block.start:04X}-${block.end - 1:04X} in the ROM and runs at "
        f"${block.org:04X} on the C64.",
        "; GENERATED by dis65xx - DO NOT EDIT. Regenerate with: python3 build.py",
        "",
        f"{'':{_INDENT}}{'CPU':{_MNEM_WIDTH}}6502",
        "",
    ]
    if external:
        lines.append("; C64 ROM entry points.")
        width = max(len(n) for n in external.values())
        for addr in sorted(external):
            lines.append(f"{external[addr]:<{max(width, 8)}} EQU     ${addr:04X}")
        lines.append("")
    lines.append(f"{'':{_INDENT}}{'ORG':{_MNEM_WIDTH}}${block.org:04X}")
    lines.append("")

    all_names = {**external, **labels}
    pending: list[int] = []

    def flush() -> None:
        while pending:
            chunk = bytes(pending[:BYTES_PER_FCB])
            del pending[:BYTES_PER_FCB]
            lines.append(f"{'':{_INDENT}}{'FCB':{_MNEM_WIDTH}}"
                         + ",".join(f"${b:02X}" for b in chunk))

    for rt, insn, byte in _decode_block(data, base, block, labels, sidecar):
        if rt in labels:
            flush()
            rom_addr = rt + block.offset
            block_comment = sidecar.block_comments.get(rom_addr)
            lines.append("")
            if block_comment:
                for line in block_comment.strip().splitlines():
                    lines.append(f"; {line}" if line else ";")
            lines.append(f"{labels[rt]}:")
        if insn is None:
            pending.append(byte)
            continue
        flush()
        body = (f"{'':{_INDENT}}{insn.mnemonic:{_MNEM_WIDTH}}"
                f"{_operand(insn, all_names)}").rstrip()
        comment = sidecar.line_comments.get(rt + block.offset)
        lines.append(f"{body:<40}; {comment}" if comment else body)
    flush()
    lines.append("")
    lines.append(f"{'':{_INDENT}}END")
    return "\n".join(lines) + "\n"
