"""Listing generation. Pure formatting — no analysis decisions are made here.

Output targets asl (Macro Assembler AS) syntax and is also accepted verbatim by
dis6801.asm, which is what enforces byte-identity.
"""

from __future__ import annotations

from dis6801.decode import Insn
from dis6801.opcodes import Mode, modes_for
from dis6801.sidecar import Sidecar
from dis6801.trace import CODE, TraceResult

BYTES_PER_FCB = 16
_INDENT = 8      # leading spaces before a mnemonic
_MNEM_WIDTH = 8  # column width the mnemonic is padded to


def format_operand(insn: Insn, sidecar: Sidecar) -> str:
    mode = insn.mode
    value = insn.operand

    if mode is Mode.INH:
        return ""
    if mode is Mode.IMM8:
        return f"#${value:02X}"
    if mode is Mode.IMM16:
        return f"#${value:04X}"
    if mode is Mode.IDX:
        return f"${value:02X},X"
    if mode is Mode.REL:
        return sidecar.labels.get(value) or f"${value:04X}"
    if mode is Mode.DIR:
        return sidecar.symbols.get(value) or f"${value:02X}"
    if mode is Mode.EXT:
        name = sidecar.symbols.get(value) or sidecar.labels.get(value)
        # Force extended when a shortest-fit assembler would choose direct.
        prefix = ">" if value < 0x100 and Mode.DIR in modes_for(insn.mnemonic) else ""
        return prefix + (name if name else f"${value:04X}")

    raise AssertionError(f"unhandled mode {mode}")  # pragma: no cover


def _instruction_line(insn: Insn, sidecar: Sidecar) -> str:
    operand = format_operand(insn, sidecar)
    body = f"{'':{_INDENT}}{insn.mnemonic:{_MNEM_WIDTH}}{operand}".rstrip()
    comment = sidecar.line_comments.get(insn.addr)
    return f"{body:<40}; {comment}" if comment else body


def _fcb_line(chunk: bytes) -> str:
    values = ",".join(f"${b:02X}" for b in chunk)
    return f"{'':{_INDENT}}{'FCB':{_MNEM_WIDTH}}{values}"


def _equ_lines(sidecar: Sidecar) -> list[str]:
    """Declare sidecar symbols so the listing is self-contained.

    format_operand() renders hardware registers and RAM locations by name. Those
    addresses live outside the ROM image, so unlike code labels nothing in the
    listing defines them — without these EQUs the listing does not assemble.
    """
    if not sidecar.symbols:
        return []
    width = max(len(n) for n in sidecar.symbols.values())
    lines = ["; Hardware registers and RAM locations referenced below.", ""]
    for addr, name in sorted(sidecar.symbols.items()):
        value = f"${addr:02X}" if addr < 0x100 else f"${addr:04X}"
        lines.append(f"{name:{max(width, _INDENT - 1)}} EQU     {value}")
    lines.append("")
    return lines


def _fdb_line(words: list[int]) -> str:
    values = ",".join(f"${w:04X}" for w in words)
    return f"{'':{_INDENT}}{'FDB':{_MNEM_WIDTH}}{values}"


def emit(data: bytes, result: TraceResult, sidecar: Sidecar) -> str:
    base = result.base
    lines: list[str] = [
        "; Commodore BTX Decoder II firmware",
        "; GENERATED by dis6801 from sidecar/decoder_ii.toml - DO NOT EDIT.",
        ";",
        "; Regenerate and verify with:  python3 build.py",
        "",
        f"{'':{_INDENT}}{'CPU':{_MNEM_WIDTH}}6801",
        "",
    ]
    lines += _equ_lines(sidecar)
    lines += [
        f"{'':{_INDENT}}{'ORG':{_MNEM_WIDTH}}${base:04X}",
        "",
    ]

    addr = base
    end = base + len(data)
    pending: list[int] = []  # unclassified bytes waiting to be flushed as FCB

    def flush() -> None:
        while pending:
            chunk = bytes(pending[:BYTES_PER_FCB])
            del pending[:BYTES_PER_FCB]
            lines.append(_fcb_line(chunk))

    while addr < end:
        label = sidecar.labels.get(addr)
        block = sidecar.block_comments.get(addr)
        region = sidecar.region_at(addr)
        insn = result.insns.get(addr)
        is_code = insn is not None and result.kind[addr - base] is CODE

        if label or block:
            flush()
            lines.append("")
            if block:
                for line in block.strip().splitlines():
                    lines.append(f"; {line}" if line else ";")
            if label:
                lines.append(f"{label}:")

        if region is not None and region.kind in ("words", "ptr_table") and not is_code:
            flush()
            count = min(8, (min(region.end, end) - addr) // 2)
            if count:
                words = [
                    int.from_bytes(data[addr - base + 2 * i: addr - base + 2 * i + 2], "big")
                    for i in range(count)
                ]
                lines.append(_fdb_line(words))
                addr += 2 * count
                continue

        if is_code:
            flush()
            lines.append(_instruction_line(insn, sidecar))
            addr = insn.end
            continue

        pending.append(data[addr - base])
        addr += 1
        # Break the FCB run at any address that carries its own annotation.
        if addr < end and (addr in sidecar.labels or addr in sidecar.block_comments):
            flush()

    flush()
    lines.append("")
    lines.append(f"{'':{_INDENT}}END")
    return "\n".join(lines) + "\n"
